# -*- coding: utf-8 -*-
"""retirement_calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17S1GPAlZQzhixfTEn4_4ZE-_DihNtA_6
"""

import streamlit as st

# Set page configuration for ICCU Bank theme
st.set_page_config(page_title="ICCU Bank Retirement Calculator", page_icon="💼", layout="centered")

# Apply custom CSS for red, white, and black theme
st.markdown(
    """
    <style>
    .main {
        background-color: #ffffff;
        color: #000000;
    }
    .stButton > button {
        color: #ffffff;
        background-color: #ff0000;
        border-color: #ff0000;
    }
    .stTextInput, .stNumberInput, .stSlider {
        border-color: #ff0000;
    }
    </style>
    """,
    unsafe_allow_html=True
)

# Title and description for the calculator
st.title("ICCU Bank Retirement Calculator")
st.write("Plan your retirement with confidence using ICCU Bank's comprehensive retirement calculator.")

# User inputs for the retirement calculator
current_age = st.number_input("Current Age", min_value=18, max_value=100, value=35)
retirement_age = st.number_input("Retirement Age", min_value=current_age, max_value=100, value=65)
current_savings = st.number_input("Current Savings ($)", min_value=0, value=50000)
annual_income = st.number_input("Annual Income ($)", min_value=0, value=80000)
savings_rate = st.slider("Expected Annual Savings Rate (%)", min_value=0, max_value=100, value=15)
annual_return = st.slider("Expected Annual Return on Investments (%)", min_value=0.0, max_value=20.0, value=6.0)
inflation_rate = st.slider("Expected Inflation Rate (%)", min_value=0.0, max_value=10.0, value=2.0)
desired_retirement_income = st.number_input("Desired Annual Retirement Income ($)", min_value=0, value=60000)
years_in_retirement = st.number_input("Years in Retirement", min_value=1, max_value=50, value=25)
social_security_income = st.number_input("Social Security or Pension Income ($)", min_value=0, value=20000)

# Convert percentage inputs to decimals for calculations
savings_rate /= 100
annual_return /= 100
inflation_rate /= 100

# Calculations
years_until_retirement = retirement_age - current_age
annual_savings = annual_income * savings_rate

# Future Value of Current Savings
fv_current_savings = current_savings * ((1 + annual_return) ** years_until_retirement)

# Future Value of Annual Contributions
fv_annual_contributions = annual_savings * (((1 + annual_return) ** years_until_retirement - 1) / annual_return)

# Total Retirement Savings at Retirement Age
total_retirement_savings = fv_current_savings + fv_annual_contributions

# Desired Retirement Income in Future Dollars
future_retirement_income = desired_retirement_income * ((1 + inflation_rate) ** years_until_retirement)

# Required Retirement Fund Calculation
annual_return_after_inflation = annual_return - inflation_rate
required_fund = (future_retirement_income - social_security_income) / annual_return_after_inflation * \
    (1 - (1 / ((1 + annual_return_after_inflation) ** years_in_retirement)))

# Calculate Shortfall or Surplus
shortfall_or_surplus = total_retirement_savings - required_fund

# Display results
st.subheader("Results")
st.write(f"Projected Savings at Retirement Age: ${total_retirement_savings:,.2f}")
st.write(f"Required Retirement Fund: ${required_fund:,.2f}")

if shortfall_or_surplus < 0:
    st.write(f"**You have a shortfall of: ${-shortfall_or_surplus:,.2f}. Consider increasing your savings rate or adjusting your retirement age or income expectations.**")
else:
    st.write(f"**You have a surplus of: ${shortfall_or_surplus:,.2f}. You are on track for retirement!**")

st.write("Thank you for using ICCU Bank's Retirement Calculator. Start planning today for a secure tomorrow!")